// Code generated by mapper generator. DO NOT EDIT.
// This file was auto-generated from user.go

package mapper_example

import (
	"time"
)

// ToUserDTO преобразует модель User в DTO UserDTO
func (m *User) ToUserDTO() *UserDTO {
	if m == nil {
		return nil
	}
	dto := &UserDTO{
		Name:      m.Name,
		Email:     m.Email,
		CreatedAt: m.CreatedAt.Format(time.RFC3339),
		Age:       m.Age,
		IsActive:  m.IsActive,
		Tags:      m.Tags,
		ID:        m.ID,
	}
	return dto
}

// UserDTOToUser создает модель User из DTO UserDTO
func UserDTOToUser(dto *UserDTO) *User {
	if dto == nil {
		return nil
	}
	model := &User{
		Name:      dto.Name,
		Email:     dto.Email,
		CreatedAt: parseTime(dto.CreatedAt),
		Age:       dto.Age,
		IsActive:  dto.IsActive,
		Tags:      dto.Tags,
		ID:        dto.ID,
	}
	return model
}

// SliceToUserDTO преобразует слайс моделей User в слайс DTO UserDTO
func SliceToUserDTO(models []User) []UserDTO {
	if models == nil {
		return nil
	}
	dtos := make([]UserDTO, len(models))
	for i := range models {
		dtos[i] = *models[i].ToUserDTO()
	}
	return dtos
}

// UserDTOSliceToUser создает слайс моделей User из слайса DTO UserDTO
func UserDTOSliceToUser(dtos []UserDTO) []User {
	if dtos == nil {
		return nil
	}
	models := make([]User, len(dtos))
	for i := range dtos {
		models[i] = *UserDTOToUser(&dtos[i])
	}
	return models
}
