// Code generated by mapper generator. DO NOT EDIT.
// This file was auto-generated from order.go

package mapper_example

import ()

// ToOrderItemDTO преобразует модель OrderItem в DTO OrderItemDTO
func (m *OrderItem) ToOrderItemDTO() *OrderItemDTO {
	if m == nil {
		return nil
	}
	dto := &OrderItemDTO{
		Quantity:  m.Quantity,
		Price:     m.Price,
		ProductID: m.ProductID,
	}
	return dto
}

// OrderItemDTOToOrderItem создает модель OrderItem из DTO OrderItemDTO
func OrderItemDTOToOrderItem(dto *OrderItemDTO) *OrderItem {
	if dto == nil {
		return nil
	}
	model := &OrderItem{
		Quantity:  dto.Quantity,
		Price:     dto.Price,
		ProductID: dto.ProductID,
	}
	return model
}

// SliceToOrderItemDTO преобразует слайс моделей OrderItem в слайс DTO OrderItemDTO
func SliceToOrderItemDTO(models []OrderItem) []OrderItemDTO {
	if models == nil {
		return nil
	}
	dtos := make([]OrderItemDTO, len(models))
	for i := range models {
		dtos[i] = *models[i].ToOrderItemDTO()
	}
	return dtos
}

// OrderItemDTOSliceToOrderItem создает слайс моделей OrderItem из слайса DTO OrderItemDTO
func OrderItemDTOSliceToOrderItem(dtos []OrderItemDTO) []OrderItem {
	if dtos == nil {
		return nil
	}
	models := make([]OrderItem, len(dtos))
	for i := range dtos {
		models[i] = *OrderItemDTOToOrderItem(&dtos[i])
	}
	return models
}
