// Code generated by mapper generator. DO NOT EDIT.
// This file was auto-generated from order.go

package mapper_example

import (
	"time"
)

// ToOrderDTO преобразует модель Order в DTO OrderDTO
func (m *Order) ToOrderDTO() *OrderDTO {
	if m == nil {
		return nil
	}
	dto := &OrderDTO{
		Total:     m.Total,
		Status:    m.Status,
		CreatedAt: m.CreatedAt.Format(time.RFC3339),
		Items:     SliceToOrderItemDTO(m.Items),
		ID:        m.ID,
		UserID:    m.UserID,
	}
	return dto
}

// OrderDTOToOrder создает модель Order из DTO OrderDTO
func OrderDTOToOrder(dto *OrderDTO) *Order {
	if dto == nil {
		return nil
	}
	model := &Order{
		Total:     dto.Total,
		Status:    dto.Status,
		CreatedAt: parseTime(dto.CreatedAt),
		Items:     OrderItemDTOSliceToOrderItem(dto.Items),
		ID:        dto.ID,
		UserID:    dto.UserID,
	}
	return model
}

// SliceToOrderDTO преобразует слайс моделей Order в слайс DTO OrderDTO
func SliceToOrderDTO(models []Order) []OrderDTO {
	if models == nil {
		return nil
	}
	dtos := make([]OrderDTO, len(models))
	for i := range models {
		dtos[i] = *models[i].ToOrderDTO()
	}
	return dtos
}

// OrderDTOSliceToOrder создает слайс моделей Order из слайса DTO OrderDTO
func OrderDTOSliceToOrder(dtos []OrderDTO) []Order {
	if dtos == nil {
		return nil
	}
	models := make([]Order, len(dtos))
	for i := range dtos {
		models[i] = *OrderDTOToOrder(&dtos[i])
	}
	return models
}
