// Code generated by mapper generator. DO NOT EDIT.
// This file was auto-generated from product.go

package mapper_example

import (
	"time"
)

// ToProductDTO преобразует модель Product в DTO ProductDTO
func (m *Product) ToProductDTO() *ProductDTO {
	if m == nil {
		return nil
	}
	dto := &ProductDTO{
		CreatedAt:   m.CreatedAt.Format(time.RFC3339),
		CategoryID:  m.CategoryID,
		ID:          m.ID,
		Name:        m.Name,
		Description: m.Description,
		Price:       m.Price,
		Stock:       m.Stock,
	}
	return dto
}

// ProductDTOToProduct создает модель Product из DTO ProductDTO
func ProductDTOToProduct(dto *ProductDTO) *Product {
	if dto == nil {
		return nil
	}
	model := &Product{
		CreatedAt:   parseTime(dto.CreatedAt),
		CategoryID:  dto.CategoryID,
		ID:          dto.ID,
		Name:        dto.Name,
		Description: dto.Description,
		Price:       dto.Price,
		Stock:       dto.Stock,
	}
	return model
}

// SliceToProductDTO преобразует слайс моделей Product в слайс DTO ProductDTO
func SliceToProductDTO(models []Product) []ProductDTO {
	if models == nil {
		return nil
	}
	dtos := make([]ProductDTO, len(models))
	for i := range models {
		dtos[i] = *models[i].ToProductDTO()
	}
	return dtos
}

// ProductDTOSliceToProduct создает слайс моделей Product из слайса DTO ProductDTO
func ProductDTOSliceToProduct(dtos []ProductDTO) []Product {
	if dtos == nil {
		return nil
	}
	models := make([]Product, len(dtos))
	for i := range dtos {
		models[i] = *ProductDTOToProduct(&dtos[i])
	}
	return models
}
