CREATE ROLE ibs WITH LOGIN PASSWORD 'ibs';
CREATE ROLE messages WITH LOGIN PASSWORD 'messages';

CREATE DATABASE testdb OWNER ibs;
CREATE DATABASE ibs OWNER ibs;
CREATE DATABASE ibs_pool OWNER ibs;
CREATE DATABASE ibs_migration OWNER ibs;
CREATE DATABASE ibs_goose OWNER ibs;
CREATE DATABASE messages OWNER messages;
